### ISSUE TITLE
Mention "blank node labels"?

### ISSUE THREAD

**Issue by hartig** [w3c/rdf-concepts#38]
Related to the discussion in https://github.com/w3c/sparql-query/issues/66, I wonder whether we should include a note in Section 3.4 (Blank Nodes) that says that the term "blank node label" is sometimes used informally as an alternative to the term "blank node identifier"?

**Comment by gkellogg** [comment]
It might be better to say that, in a concrete syntax, a blank node might be labeled with an identifier. RDF Canonicalization has faced a similar dilemma with label vs identifier.

I asked Chat GPT for the distinction:

> The distinction between blank node labels and blank node identifiers is that blank node labels are locally scoped identifiers that are generated by RDF document authors, whereas blank node identifiers are system-generated identifiers that are used by RDF processors and triple stores. The use of blank node identifiers can be helpful in cases where the RDF data is being transformed or merged by different systems, and globally unique blank node identifiers can be generated by these systems to ensure that blank nodes are treated consistently across different graphs.

somewhat made up, but maybe useful.

**Comment by afs** [comment]
I did a quick assessment of the situation by grep-counting for "identifier" and "node label" and some looking over the documents.

- we are using the fully qualified terminology "blank node identifer" and "blank node label"
- the word "identifier" occurs in other ways as well.
- concepts, semantics and rdf-xml are consistently using "blank node identifier" with label only for rdfs:label.
- n-triples, n-quads, turtle use "blank node label"
- Grammars use `BLANK_NODE_LABEL` - I didn't include that in the counts.
- There is use of phrase "term identifier" in security sections . This is new to RDF 1.2. 

e.g.
```
grep label rdf-{concepts,semantics}/spec/index.html
rdf-concepts/spec/index.html:  <p>RDF can express data which is presented to the user, such as RDF Schema labels.
rdf-semantics/spec/index.html:        rdfs:label</code></td>
rdf-semantics/spec/index.html:    and <code>rdfs:label</code> are included here because some constraints which
rdf-semantics/spec/index.html:        rdfs:label rdfs:domain rdfs:Resource .<br/>
rdf-semantics/spec/index.html:        rdfs:label rdfs:range rdfs:Literal .<br/>
rdf-semantics/spec/index.html:        rdfs:label rdf:type rdf:Property .<br/>
```

Turtle:
- Almost all use is in one section (.e.g https://w3c.github.io/rdf-turtle/spec/index.html#BNodes ("unlabeled" in the next).
- "Repeated use of the same blank node label identifies the same RDF blank node." was the only problematic text I found.

NT/NQ:
- Similar section to Turtle.

SPARQL:
In SPARQL, it is mainly query and it mostly uses "blank node label" (~17) with some use of "blank node identifier" (4).
That can be updated.

_Other:_
https://en.wikipedia.org/wiki/Blank_node :: blank node identifier

`BLANK_NODE_LABEL` - this does not leak further than grammar and the parsing section.  It is the concrete choice for "blank node identifier" in these syntaxes.

RDF Canonicalization probably needs specific terminology for its own needs such as "system identifier" - there would be no harm adding it in concepts (other than having termninology that is never used, and is another use of "identifier") but equally it might be clearer to define it in RDF Canonicalization because it is important to the algorithms. RDF Concepts etc doesn't need the internal id concept; it is possible to implement RDF without "system identifiers".

**Comment by afs** [comment]
The idea of adding a note in Section 3.4 (Blank Nodes) is a good one. It could be added in the existing note.

**Comment by afs** [comment]
RDF Concepts exports with text "blank node identifers" - plural (the #fragment is OK - there iare both singular and plural versions).

How does reSpec pick up or allow control of the export section text?

**Comment by gkellogg** [comment]
> RDF Concepts exports with text "blank node identifers" - plural (the #fragment is OK - there iare both singular and plural versions).

> How does reSpec pick up or allow control of the export section text?

Note that the spec previously exported the term "blank node identifiers" as `#dfn-blank-node-identifiers`, which is preserved in `<span id="dfn-blank-node-identifiers"><!-- obsolete term--></span>`. Although the text still says "blank node identifiers", the term is defined as `#dfn-blank-node-identifier` explicitly. ReSpec has rules for turning rules for references with the plural form into the singular, so `<a>blank node identifiers</a>` will resolve to `#dfn-blank-node-identifier` if it is defined.

**Comment by TallTed** [comment]
> I asked Chat GPT

ChatGPT can provide assistance in many areas, especially when you include current data in your prompts, but it's important to note that its primary corpus ends years ago, depending on the version you're talking to. As v4.0 can tell you:
> My knowledge base extends up to September 2021. I do not have information on events, developments, or advancements that have occurred since then.

**Comment by hartig** [comment]
@TallTed, I agree, but this belongs in the repo for the Turtle spec. I have created an issue over there. See: https://github.com/w3c/rdf-turtle/issues/22
