### ISSUE TITLE
adequacy of base direction

### ISSUE THREAD

**Issue by pfps** [w3c/rdf-concepts#61]
This is a clarification of a portion of #51.  

The issue is whether initial base direction and initial language is adequate for display of multi-language strings in the absence of explicit directional control inside the string.  One difficult situation is a sequence of RTL text separated by punctuation inside an LTR string.  Without explicit directional control inside the string, the elements of the sequence will be displayed RTL, i.e., backwards.  

The problem is discussed in https://unicode.org/reports/tr9/ Section 6.4 where several even worse situations are given.

**Comment by TallTed** [comment]
We were discussing a comma-separated, ordered list, where items within the list varied in their directionality, and could be reordered when displayed (at least) with different base directionality.

**Comment by pfps** [comment]
Here is an example of multi-lingual text that displays badly without internal information on direction:

ماركة A123B (1920 x 1080) 36" شاشة الكمبيوتر، 75 Hz، 4 مللي ثانية

This is taken from https://www.w3.org/TR/international-specs/#example-example-of-bidirectional-interference-across-boundaries

**Comment by ktk** [comment]
@r12a ping, this is the followup issue we discussed this morning.

**Comment by gkellogg** [comment]
I would think that in HTML you would need to separate these elements with spans, possibly setting `@dir/@lang` on each span. Is it too much to think that there's a single piece of metadata that can be used for arbitrary strings with internal bidi-complex direction changes? In RDF, you might model this as a list of directional language-tagged strings.

**Comment by aphillips** [comment]
@gkellogg is correct (and the example in specdev is illustrating this exactly). The base paragraph direction does not deal with the _internal_ bidirectional needs of a given string. However, it does provide the information necessary for _isolating_ and _rendering_  that string by whomever receives it.

The example in specdev shows a number of mixed directional strings being concatenated together in what, I hope, is a reasonable example of something a real implementation might try to do. When base direction metadata is supplied for each substring, the result is legible. 

Our document [String-Meta](https://w3c.github.io/string-meta) says near the start what the purpose of the base direction determination is about (emphasis added):

> In this document we are concerned with identifying the [paragraph direction](https://www.w3.org/TR/i18n-glossary/#dfn-paragraph-direction) of a whole string and how to transmit and apply the paragraph direction when displaying strings in various contexts. **We do not talk about how to determine the direction or display of runs of text within a string.**
>
> The [bidi algorithm](https://www.w3.org/TR/i18n-glossary/#dfn-unicode-bidi-algorithm) is primarily focused on arranging adjacent characters, based on character properties. The base direction dictates (a) the visual order and direction in which runs of strongly-typed [LTR](https://www.w3.org/TR/i18n-glossary/#dfn-left-to-right) and [RTL](https://www.w3.org/TR/i18n-glossary/#dfn-right-to-left) character are displayed, and (b) where there are weakly-directional or neutral characters such as punctuation, the placement of those items relative to the other content.

There is also a big green note box near the start that says in part:

> If you are unfamiliar with bidirectional or right-to-left text, [here](https://www.w3.org/International/articles/inline-bidi-markup/uba-basics) is a basic introduction here. This will give you a basic grasp of how the [Unicode Bidirectional Algorithm](https://www.w3.org/TR/i18n-glossary/#dfn-unicode-bidi-algorithm) works and the interplay between it and the base direction, which will stand you in good stead for reading this document.

I realize that understanding bidirectional text can be difficult, but it is important to understand the fundamentals. Actually, I think that your questions help convey the need for base direction: once a given string is internally ready for (bidirectional) display, it still needs its base direction when you go to display it in order to prevent problems with interactions with the surrounding document. 

Does that help?

I think @r12a might be able to supply some clarity as well.
