### ISSUE TITLE
XML schema datatypes double and float do not specify lexical-to-value map

### ISSUE THREAD

**Issue by pfps** [w3c/rdf-concepts#85]
In XML Schema datatypes 1.1 double and float the lexical-to-value map can vary.  This is a change from 1.0 but breaks the definition of RDF datatypes.

Concepts should be updated to require the mapping defined in XML Schema datatypes 1.1, which was the required mapping in XML Schema datatypes 1.0.

**Comment by IS4Code** [comment]
No. It is not the responsibility of RDF Concepts to affect the interpretation of those datatypes in a way that would be conflicting with XML Schema. If anything the standard might discourage from using ambiguous values, but anything else should be left to the interpretation of RDF terms.

The point of using `xsd:float` and `xsd:double` is to *rely* on their fast native implementations and efficient storage. It would be an implementational disaster to mandate a different way of parsing than what is already used for XML Schema everywhere. It is definitely unfortunate that the actual values could be inconsistently produced, but perhaps that is simply what you get by using `xsd:float` and `xsd:double` ‒ you can't make them precise.

**Comment by domel** [comment]
Indeed, the update to the XML specification introduces the possibility of different lexical-to-value maps, which necessitates that RDF choose one of them. As you noted, the most obvious choice would be to maintain consistency with the map mandated by the previous version of the XML specification.

However, a crucial question arises: what happens if an RDF implementation is already using a different map that will not be chosen as the standard in RDF? In such a case, significant compatibility issues may arise. The RDF implementation might not be able to directly use the existing XML datatypes implementation, leading to the potential need for substantial modifications in the systems to ensure compliance with the chosen RDF standard.

**Comment by gkellogg** [comment]
@pfps can you suggest some specific wording and references to add to the float and double mappings? Or, better yet, create a PR for this.

**Comment by pfps** [comment]
The solution for rdf:JSON, slightly generalized, should work here.
