### ISSUE TITLE
remove rdf:JSON if it doesn't meet the requirements of an RDF datatype

### ISSUE THREAD

**Issue by pfps** [w3c/rdf-concepts#90]
If rdf:JSON does not meet the requirements of an RDF datatype then it should be removed from RDF concepts.

**Comment by IS4Code** [comment]
Thesis please?

**Comment by pfps** [comment]
There are requirements for RDF datatypes in RDF Concepts.  The description of rdf:JSON does not meet these requirements.

**Comment by domel** [comment]
Which fragment RDF Concepts define these requirements?

**Comment by pfps** [comment]
https://w3c.github.io/rdf-concepts/spec/#section-Datatypes

**Comment by domel** [comment]
I can't find a relevant quote in this fragment that would support your opinion.

**Comment by pfps** [comment]
For example, "A [JSON Array](https://pr-preview.s3.amazonaws.com/w3c/rdf-concepts/pull/RFC8259#section-5) is mapped to a [list](https://infra.spec.whatwg.org/#list) by performing this mapping on each array value."  is inadequate because it does not say how the list is constructed.   

A large part of specifications is taking what might appear to be obvious and writing it down so that there can be no misunderstandings.

The value space is has *ordered* maps.   What is the order?  How is it supposed to be "ignored"?

"A [JSON String](https://pr-preview.s3.amazonaws.com/w3c/rdf-concepts/pull/RFC8259#section-7) is mapped to a [string](https://pr-preview.s3.amazonaws.com/w3c/rdf-concepts/pull/66.html#dfn-rdf-string)."  What is the string?

And more.

**Comment by gkellogg** [comment]
> For example, "A [JSON Array](https://pr-preview.s3.amazonaws.com/w3c/rdf-concepts/pull/RFC8259#section-5) is mapped to a [list](https://infra.spec.whatwg.org/#list) by performing this mapping on each array value." is inadequate because it does not say how the list is constructed.

You may quibble with the wording, but the spec does address how to map a JSON Array to a list:

> A [JSON Array](https://www.w3.org/TR/rdf12-concepts/RFC8259#section-5) is mapped to a [list](https://infra.spec.whatwg.org/#list) by performing this mapping on each array value.

Rather than saying that it does nothing, you might instead suggest how this definition can be improved. Perhaps by being even more exploit by saying "... by creating a new list which each value of that list is created by performing this mapping on that value and placing it at the same index within the target list." IMO, the meaning is already pretty clear.

> A large part of specifications is taking what might appear to be obvious and writing it down so that there can be no misunderstandings.
> 
> The value space is has _ordered_ maps. What is the order? How is it supposed to be "ignored"?

From the definition of map equality, order doesn't matter, thus it can be ignored.

> A [JSON Object](https://www.w3.org/TR/rdf12-concepts/RFC8259#section-4) is mapped to a [map](https://infra.spec.whatwg.org/#ordered-map) by transforming each object member into a [map entry](https://infra.spec.whatwg.org/#map-entry) with the [key](https://infra.spec.whatwg.org/#map-key) taken from the member name and [value](https://infra.spec.whatwg.org/#map-value) taken by performing this mapping to the member value. [Map entries](https://infra.spec.whatwg.org/#map-entry) are treated as being unordered.

Also, IMO, the last sentence doesn't add any value as order never comes into any operation on this component.

> "A [JSON String](https://pr-preview.s3.amazonaws.com/w3c/rdf-concepts/pull/RFC8259#section-7) is mapped to a [string](https://pr-preview.s3.amazonaws.com/w3c/rdf-concepts/pull/66.html#dfn-rdf-string)." What is the string?

More wording could be taken from, say, [Turtle](https://www.w3.org/TR/rdf12-turtle/#grammar-production-STRING_LITERAL_QUOTE) on the specific mapping:

> A JSON string is used with escape sequences unescaped to form the RDF string of the lexical form.

Please make (or respond to) suggestions for improving the wording rather than trow bricks at the entire effort.

**Comment by pfps** [comment]
There are still problems with maps.

**Comment by gkellogg** [comment]
> There are still problems with maps.

Create an issue with a specific issue, or re-open one that was closed. Other than order/unorder, I believe I addressed your concerns and had suggested changes open for a few days without additional comment.
